version: "3.5"

services:
  app: 
    build:
      context: .
    container_name: app
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:8080
    ports:
      - "8080:8080"

